version: '3.6'

services:
  redis:
    container_name: redis
    image: redis:5.0.9-alpine
    restart: on-failure
    networks:
      hyperion:
        ipv4_address: 172.19.0.11


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3-management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/hyperion
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks:
      hyperion:
        ipv4_address: 172.19.0.12

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    restart: on-failure
    environment:
      - discovery.type=single-node
      - cluster.name=es-cluster
      - node.name=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      hyperion:
        ipv4_address: 172.19.0.13

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.1
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
    ports:
      - 5601:5601
    networks:
      hyperion:
        ipv4_address: 172.19.0.14
    extra_hosts:
      - "redis:172.19.0.11"
      - "rabbitmq:172.19.0.12"
      - "elasticsearch:172.19.0.13"
      - "kibana:172.19.0.14"
      - "eosio-node:172.19.0.15"
      - "hyperion-indexer:172.19.0.16"
      - "hyperion-api:172.19.0.17"
    depends_on:
      - elasticsearch

  eosio-node:
    container_name: eosio-node
    image: boscore/bos:v3.0.8
    volumes:
      - ./eosio/data/:/home/eosio/data/
      - ./eosio/config/:/home/eosio/config/
      - ./scripts/:/home/eosio/scripts/
    ports:
      - 8888:8888
    networks:
      hyperion:
        ipv4_address: 172.19.0.15
    extra_hosts:
      - "redis:172.19.0.11"
      - "rabbitmq:172.19.0.12"
      - "elasticsearch:172.19.0.13"
      - "kibana:172.19.0.14"
      - "eosio-node:172.19.0.15"
      - "hyperion-indexer:172.19.0.16"
      - "hyperion-api:172.19.0.17"
    command: bash -c "/home/eosio/scripts/run-nodeos.sh true  ${SNAPSHOT:-""}"

  hyperion-indexer:
    container_name: hyperion-indexer
    image: zhopen/hyperion:3.1.0-beta.4 
    restart: on-failure
    depends_on:
      - elasticsearch
      - redis
      - rabbitmq
      - eosio-node
    volumes:
      - ./hyperion/config/connections.json:/hyperion-history-api/connections.json
      - ./hyperion/config/ecosystem.config.js:/hyperion-history-api/ecosystem.config.js
      - ./hyperion/config/chains/:/hyperion-history-api/chains/
      - ./scripts/:/home/hyperion/scripts/
    networks:
      hyperion:
        ipv4_address: 172.19.0.16
    extra_hosts:
      - "redis:172.19.0.11"
      - "rabbitmq:172.19.0.12"
      - "elasticsearch:172.19.0.13"
      - "kibana:172.19.0.14"
      - "eosio-node:172.19.0.15"
      - "hyperion-indexer:172.19.0.16"
      - "hyperion-api:172.19.0.17"
    command: bash -c "/home/hyperion/scripts/run-hyperion.sh ${SCRIPT:-false} eos-indexer"

  hyperion-api:
    container_name: hyperion-api
    image: zhopen/hyperion:3.1.0-beta.4
    restart: on-failure
    ports:
      - 7000:7000
    depends_on:
      - hyperion-indexer
    volumes:
      - ./hyperion/config/connections.json:/hyperion-history-api/connections.json
      - ./hyperion/config/ecosystem.config.js:/hyperion-history-api/ecosystem.config.js
      - ./hyperion/config/chains/:/hyperion-history-api/chains/
      - ./scripts/:/home/hyperion/scripts/
    networks:
      hyperion:
        ipv4_address: 172.19.0.17
    extra_hosts:
      - "redis:172.19.0.11"
      - "rabbitmq:172.19.0.12"
      - "elasticsearch:172.19.0.13"
      - "kibana:172.19.0.14"
      - "eosio-node:172.19.0.15"
      - "hyperion-indexer:172.19.0.16"
      - "hyperion-api:172.19.0.17"    
    command: bash -c "/home/hyperion/scripts/run-hyperion.sh ${SCRIPT:-false} eos-api"

networks:
  hyperion:
    external: true
